import { test, expect } from '@playwright/test'

async function create(request, path, data) {
  const response = await request.post('/api/v1/' + path, { data })
  expect(response.ok(), await response.text()).toBeTruthy()
  return response.json()
}

async function selectSaved(page, section, name) {
  await section.locator('.el-select').first().click()
  await page.getByRole('option', { name: new RegExp(name) }).click()
}

test('saved instructions, pipelines and criteria can be read and edited as new copies', async ({ page, request }) => {
  test.setTimeout(90000)
  const suffix = Date.now()
  const prompt = await create(request, 'prompts', { name: 'editable-prompt-' + suffix, template: 'Original: {{text}}' })
  const pipeline = await create(request, 'pipelines', { name: 'editable-pipeline-' + suffix })
  const suite = await create(request, 'evaluation-suites', { name: 'editable-suite-' + suffix, criteria: [{ key: 'accuracy', description: 'Original criterion', weight: 1 }], quality_threshold: 0.7 })
  await page.goto('/experiments?view=settings')

  const promptEditor = page.locator('.prompt-editor')
  await selectSaved(page, promptEditor, prompt.name)
  await expect(promptEditor.getByRole('textbox', { name: 'Текст инструкции', exact: true })).toHaveValue('Original: {{text}}')
  await promptEditor.getByRole('textbox', { name: 'Название инструкции', exact: true }).fill('changed-prompt-' + suffix)
  await promptEditor.getByRole('textbox', { name: 'Текст инструкции', exact: true }).fill('Line one\n{{text | trim}}')
  await promptEditor.getByRole('button', { name: 'Сохранить новую копию инструкции', exact: true }).click()
  await expect(promptEditor.getByText(/строка 2, столбец 1/)).toBeVisible()
  await promptEditor.getByRole('textbox', { name: 'Текст инструкции', exact: true }).fill('Changed: {{input.text}}')
  await promptEditor.getByRole('button', { name: 'Сохранить новую копию инструкции', exact: true }).click()
  await expect(promptEditor.getByText(/Инструкция сохранена и выбрана/)).toBeVisible()

  const pipelineEditor = page.locator('.pipeline-editor')
  await selectSaved(page, pipelineEditor, pipeline.name)
  await expect(pipelineEditor.getByRole('textbox', { name: 'Название схемы', exact: true })).toHaveValue(pipeline.name)
  await expect(pipelineEditor.getByText(/Это не схема ответа/)).toBeVisible()
  await pipelineEditor.getByText('Техническое представление схемы', { exact: true }).click()
  await expect(pipelineEditor.locator('pre')).toContainText('generate')
  await pipelineEditor.getByRole('textbox', { name: 'Название схемы', exact: true }).fill('changed-pipeline-' + suffix)
  await pipelineEditor.getByRole('button', { name: 'Сохранить новую копию схемы', exact: true }).click()
  await expect(pipelineEditor.getByText(/Схема сохранена и выбрана/)).toBeVisible()

  const suiteEditor = page.locator('.suite-editor')
  await selectSaved(page, suiteEditor, suite.name)
  await expect(suiteEditor.getByRole('textbox', { name: 'Что оценивать 1', exact: true })).toHaveValue('Original criterion')
  await suiteEditor.getByRole('textbox', { name: 'Название правил', exact: true }).fill('changed-suite-' + suffix)
  await suiteEditor.getByRole('button', { name: 'Добавить критерий', exact: true }).click()
  await suiteEditor.getByRole('textbox', { name: 'Код критерия 2', exact: true }).fill('coverage')
  await suiteEditor.getByRole('textbox', { name: 'Что оценивать 2', exact: true }).fill('Coverage of reference facts')
  await suiteEditor.getByRole('button', { name: 'Сохранить новую копию правил', exact: true }).click()
  await expect(suiteEditor.getByText(/Сумма весов должна равняться 1/)).toBeVisible()
  await suiteEditor.locator('.el-input-number input').first().fill('0.5')
  await suiteEditor.locator('.el-input-number input').first().press('Tab')
  await suiteEditor.getByRole('button', { name: 'Сохранить новую копию правил', exact: true }).click()
  await expect(suiteEditor.getByText(/Правила сохранены/)).toBeVisible()

  const prompts = await (await request.get('/api/v1/prompts')).json()
  expect(prompts.find((item) => item.id === prompt.id).template).toBe('Original: {{text}}')
  expect(prompts.find((item) => item.name === 'changed-prompt-' + suffix).template).toBe('Changed: {{input.text}}')
  const pipelines = await (await request.get('/api/v1/pipelines')).json()
  expect(pipelines.find((item) => item.id === pipeline.id).name).toBe(pipeline.name)
  expect(pipelines.find((item) => item.name === 'changed-pipeline-' + suffix).id).not.toBe(pipeline.id)
  const suites = await (await request.get('/api/v1/evaluation-suites')).json()
  expect(suites.find((item) => item.id === suite.id).evaluators_json[0].criteria).toHaveLength(1)
  expect(suites.find((item) => item.name === 'changed-suite-' + suffix).evaluators_json[0].criteria).toHaveLength(2)

  await page.reload()
  await selectSaved(page, promptEditor, 'changed-prompt-' + suffix)
  await expect(promptEditor.getByRole('textbox', { name: 'Текст инструкции', exact: true })).toHaveValue('Changed: {{input.text}}')
})

test('preview and run errors stay next to the action buttons', async ({ page, request }) => {
  test.setTimeout(60000)
  const suffix = Date.now()
  const dataset = await create(request, 'datasets', { name: 'preview-data-' + suffix })
  await create(request, 'datasets/' + dataset.draft_version_id + '/items:commit', [{ external_id: 'sample', input: { text: 'preview sample' } }])
  await create(request, 'datasets/' + dataset.draft_version_id + ':publish')
  const invalidForDataset = await create(request, 'prompts', { name: 'missing-field-' + suffix, template: '{{missing}}' })
  const valid = await create(request, 'prompts', { name: 'valid-preview-' + suffix, template: 'Summary: {{input.text}}' })
  const pipeline = await create(request, 'pipelines', { name: 'preview-pipeline-' + suffix })
  const route = await create(request, 'model-routes', { provider_name: 'offline', model_identifier: 'preview-model-' + suffix })
  await page.addInitScript((selection) => sessionStorage.setItem('experiment-selection', JSON.stringify(selection)), {
    datasetVersionId: dataset.draft_version_id, promptVersionId: invalidForDataset.id, pipelineVersionId: pipeline.id, routeIds: [route.id],
  })
  await page.goto('/experiments')
  const actions = page.locator('.run-actions')
  await actions.getByRole('button', { name: 'Оценить объём', exact: true }).click()
  await expect(actions.getByRole('alert')).toContainText('missing')
  await expect(actions.getByRole('alert')).toBeInViewport()
  await actions.getByRole('button', { name: 'Запустить выбранную конфигурацию', exact: true }).click()
  await expect(actions.getByRole('alert')).toContainText('Строка датасета №1')
  await expect(actions.getByRole('alert')).toBeInViewport()
  await page.locator('.run-form .el-select').nth(1).click()
  await page.getByRole('option', { name: new RegExp(valid.name) }).click()
  await actions.getByRole('button', { name: 'Показать инструкцию для первой строки', exact: true }).click()
  await expect(actions.locator('pre')).toHaveText('Summary: preview sample')
  await actions.getByRole('button', { name: 'Скрыть инструкцию', exact: true }).click()
  await expect(actions.locator('pre')).toBeHidden()
  await actions.getByRole('button', { name: 'Показать сохранённую инструкцию', exact: true }).click()
  await expect(actions.locator('pre')).toHaveText('Summary: preview sample')
  await expect(actions.getByRole('alert')).toHaveCount(0)
})
